#!/bin/sh

tmpfile=/tmp/screnum.tmp

parent=$(ps -p ${PPID} -o ppid --noheaders | sed 's/\ //g')
session=$(screen -ls | egrep "^[[:blank:]]${parent}\." | awk '{print $1}' | cut -d. -f2-)

screen -D -m -S screnum &
sleep 10 && screen -S screnum -p 0 -X height 60
screen -S screnum -p 0 -X stuff "screen -x ${session} -p =
"
sleep 1 && screen -S screnum -p 0 -X hardcopy ${tmpfile}
screen -S screnum -p 0 -X kill

windowlist=$(awk '/^\ +[0-9]+\ / {print $1}' ${tmpfile})

if [ "${session}" = '' ] ;then
  echo "Can't get session name"
  exit
fi

sleep 1

inum=0
for window in ${windowlist} ;do
  if [ ${window} -gt ${inum} ] ;then
    screen -S ${session} -p ${window} -X number ${inum}
  fi
  inum=$((${inum}+1))
done

rm ${tmpfile}
