name: build

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build-deb:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Setup environment
        run: |
            sudo apt-get update
            sudo apt-get install -qy --no-install-recommends gettext-base moreutils lintian

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build package
        run: |
          debian/build.sh \
            --name=stwalkerster-environment \
            --distro=all

      - name: Lintian
        run: lintian --suppress-tags no-changelog,no-copyright-file *.deb

      - name: Configure staging AWS credentials
        if: github.ref == 'refs/heads/master'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::098014529583:role/apt-repo/apt-repo-staging

      - name: Configure production AWS credentials
        if: github.ref_type == 'tag'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::098014529583:role/apt-repo/apt-repo-production

      - name: Upload package to staging repo
        if: github.ref == 'refs/heads/master'
        run: |
          sudo gem install deb-s3
          deb-s3 upload \
              --arch=all \
              --bucket=stwalkerster-098014529583-apt \
              --codename=all \
              --prefix="staging/" \
              --visibility=private \
              --preserve-versions \
              *.deb

      - name: Upload package to production repo
        if: github.ref_type == 'tag'
        run: |
          sudo gem install deb-s3
          deb-s3 upload \
              --arch=all \
              --bucket=stwalkerster-098014529583-apt \
              --codename=all \
              --prefix="production/" \
              --visibility=private \
              --preserve-versions \
              *.deb
